
# Site settings
highlighter: pygments

title : Simple Blog (mauriziopaul)
author :
  name : Paul L. Maurizio 
  github : mauriziopaul
  twitter : TweetNTD
  feedburner : nil
# email : paul.maurizio@gmail.com
description : >
  This is the site for Paul Maurizio's GitHub pages blog, discussing research at the intersection of 
  statistical genetics and host-pathogen interactions.
production_url : https://mauriziopaul.github.io/blog
baseurl : "/blog" # the subpath of your site, e.g. /blog
url : "http://mauriziopaul.github.io" # the base hostname & protocol for your site
twitter_username : TweetNTD
github_username :  mauriziopaul

# Build settings
markdown : kramdown
kramdown :
    input : GFM
