# Site settings
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "License.md", "Gemfile", "Gemfile.lock"]
highlighter: rouge
future: false

title : Propagating Uncertainty | a statistical modeling blog
author : 
  name : Paul L. Maurizio 
  github : mauriziopaul
  twitter : TweetNTD
  feedburner : nil
# email : maurizio@alumni.unc.edu
description : Statistical Genetics, <br> Genomics &amp; Immunity
production_url : https://mauriziopaul.github.io/blog
baseurl : "/blog" # the subpath of the site
url : "http://mauriziopaul.github.io" # the base hostname & protocol for your site
twitter_username : TweetNTD
github_username :  mauriziopaul

# Build settings
markdown : kramdown
kramdown :
    input : GFM
